### PR TITLE
Rework agents.ipynb

### PR DESCRIPTION
**Pull request by rajatjain1997**
This PR contains improvements related to `agents.ipynb` notebook.

- Made changes to `agents.ipynb` to improve its reading flow.
- Re-implemented a wrong implementation of `EnergeticBlindDog` where the agent program could see the state of the agent by defining a global variable.
- Merged non-graphic implementation of `Park2D` with the graphics one.
- Fixed issue #1030 using the second approach.

**Note:** `agents.ipynb` has been stripped of its output cells before being commited to git. This is because jupyter notebooks cache all outputs (including execution count) in the `ipynb` file. This leads to a few problems while working with any VCS:
 - Merge conflicts occur even when two authors work on separate sections of the same file (since execution count or python version are bound to be different)
 - It is tough to detect errors (See #1030 )
 - PR review process becomes difficult since diff becomes unnecessarily bloated with output details.

### CODE REVIEW

**Comment by MrDupin** [comment]
I like the new structure. Didn't notice any major issues when looking at the ipynb code (haven't compiled it though).

Looks good!

**Comment by rajatjain1997** [comment]
Thanks for the review. I'm sure that the code compiles and runs. Should we modify the contribution guide to ask contributors to strip all outputs from notebooks before they commit?

**P.S.:** `nbstripoutput` is an amazing utility for this.

**Comment by dshahid380** [comment]
I would like to fix this issue.

**Comment by MrDupin** [comment]
Output should be shown wherever possible. A lot of students may want to just read the notebooks online at GitHub. The rule of thumb is, show the output unless it is not convenient to do so (for example, when you are trying to print a very long list; in that case it would be best if only part of it was printed).

**Comment by rajatjain1997** [comment]
That's a great point. However, since we have binder setup for online viewing, I thought we wanted to encourage students to run code as much as possible. But yeah, looking at output on GitHub is super-convinenent and may be something that a lot of students do.

**Pull request merged**
