### PR TITLE
Typo in bold formatting.

### PR DESCRIPTION
**Pull request by sampadsaha5**
Corrected a bad bold formatting in `agents.ipynb`.

### CODE REVIEW

**Comment by sampadsaha5** [comment]
@reachtarunhere Can you please review this PR?

**Comment by reachtarunhere** [comment]
Thank You for the PR. I am not sure if the commit changing Python version locally is required? Can you please clean that up in a new PR or here itself?

**Comment by sampadsaha5** [comment]
@reachtarunhere You are welcome. I have cleaned up the change.

**Comment by sampadsaha5** [comment]
@reachtarunhere Can you please restart the build?

**Comment by reachtarunhere** [comment]
@sampadsaha5 I feel that the build issue is fixed now. Unfortunately Travis is still using the older config file while running the build for this PR. It should work if you will create a new PR.

**Pull request closed without merging**
