### PR TITLE
Added utils.ipynb

### PR DESCRIPTION
**Pull request by SkAdilina**
utils.ipynb now contains Queue, FIFOQueue and PriorityQueue

### CODE REVIEW

**Comment by apb7** [comment]
@MrDupin and @SkAdilina : Do we actually require a notebook for utilities? We use notebooks to explain and visualize various ideas and concepts of AI whereas utilities _help_ us to do so. They do not actually represent a concept. Please correct me if I am wrong!  
Thanks!

**Comment by SkAdilina** [comment]
@apb7 I am definitely not an expert on this, so I won't be able to correct you. However, [this](https://github.com/aimacode/aima-python/blob/master/README.md#index-of-algorithms) is where I saw that Queue is yet to be included in the Notebook, so I went ahead and added it.

**Comment by apb7** [comment]
Okay, let's wait for @norvig and @MrDupin then :)

**Comment by MrDupin** [comment]
Hmm, you are right that it seems like we want a notebook for utils with the `Queue` in the README. I personally think such a notebook is not necessary, so maybe we want to remove `Queue` from the list of algorithms, or add a 'Not Needed' mark on the 'Notebook' section.

It is up to @norvig though.

**Comment by norvig** [comment]
I don't think we need a notebook for utilities, including Queue. I think we can just import the code.

**Comment by MrDupin** [comment]
I am afraid since Mr. Norvig said we don't need a notebook for utilities, I have to close this.

Thanks for the work though. Keep it up!

**Pull request closed without merging**
