### PR TITLE
Fix learning tests

### PR DESCRIPTION
**Pull request by lucasmoura**
Two tests on test_learning.py are failing now. That's because they are testing code that still have not been merged. Both tests address the following MR: #435.

This MR simply remove these tests.

However, I do believe that both of these tests should be added to #435.

### CODE REVIEW

**Comment by MrDupin** [comment]
The tests you mentioned *are* added in #435.

I unfortunately added the tests in another PR, which I didn't think would get merged before #435. My bad.

**Comment by lucasmoura** [comment]
No problem, it happens :)

**Comment by MrDupin** [comment]
I just want to note that this PR should be merged **only** if #435 is declined. Otherwise there is no point, and might possibly cause conflicts with other PRs dealing with `test_learning`.

**Comment by norvig** [comment]
Thanks for this -- my mistake in taking a few days off and getting behind in merges, and taking them in the wrong order. Glad to have this fix!

**Pull request merged**
