### PR TITLE
Updating README Index of Code to reflect actual implementation status.

### PR DESCRIPTION
**Pull request by thundergolfer**
I am wanting to contribute to this repo, so I went through went to the Index of Code to find unimplemented algorithms from the book.

I found the LRTA* Agent, though listed as unimplemented, was actually implemented. I then went through and checked the status of all apparently unimplemented methods.

I found a few more that were actually implemented, and one that was not implemented despite being listed as complete.

I have altered the Index of Code table to fix this.

Note: This a resubmission of a previous pull request without an unnecessary code change

### CODE REVIEW

**Comment by thundergolfer** [comment]
@SnShine just resubmitted without the problematic code. These changes are only to the README and it now includes two extra implemented algorithms that I found. I really wanted to do the BackPropLearner but damn, already done haha

**Comment by reachtarunhere** [comment]
@thundergolfer Apologies I just updated the README and it is creating conflicts. Can you please update your local repo and update this or send another PR? Thanks :)

**Comment by thundergolfer** [comment]
@reachtarunhere yeah will do

**Comment by reachtarunhere** [comment]
@thundergolfer I guess this is still an older version.

**Comment by thundergolfer** [comment]
@reachtarunhere seems to be fixed now.

**Comment by reachtarunhere** [comment]
@thundergolfer Currently index.ipnb contains the AIMA Python Binder Index. The commit https://github.com/aimacode/aima-python/pull/235/commits/c60d8eba8a791be890c4cf9eec359cd1aa0eef34 has been overwritten. So you need to clone again and make changes.

**Comment by thundergolfer** [comment]
@reachtarunhere ah really damn. OK on it

**Pull request closed without merging**
