### PR TITLE
Refactor backpropagation

### PR DESCRIPTION
**Pull request by lucasmoura**
Just some minor refactoring in the BackPropagationLearner, such as:

* Create a function to initialize the random weights
* Create a function to calculate the sigmoid value

### CODE REVIEW

**Comment by MrDupin** [comment]
Nice work. A couple of suggestions:

* In `utils.py` we have a function for the sigmoid. It takes as input a number and returns a number. It would be better if we had the same for its derivative. I suggest you write `sigmoid_derivative`, with arguments a number instead of a node. Then you could call this function with `sigmoid_derivative(o_nodes[i].value)`. Also, as a name, `sigmoid_derivative` is cleaner than `sigmoid_derivative_value`, since we also have `sigmoid` and not `sigmoid_value`.

* For the random weight function, in my opinion a better name would simply be `random_weights`. Currently the call to the function is too long (almost as long as the code it replaces). If `random_weights` isn't taken, I would suggest renaming your function to that.

**Comment by lucasmoura** [comment]
Good suggestions, I will work on them. Thanks :)

**Comment by MrDupin** [comment]
There are some conflicts now. May you resolve them?

**Comment by lucasmoura** [comment]
@MrDupin Done

**Comment by MrDupin** [comment]
Thanks.

**Pull request merged**
