### PR TITLE
Implemented HybridWumpusAgent

### PR DESCRIPTION
**Pull request by kunwar31**
Solves part of #641 ( implement HybridWumpusAgent ) and therefore part of #817

### CODE REVIEW

**Comment by ad71** [comment]
Nice work! Are you going to complete the HybridWumpusAgent class too?

**Comment by kunwar31** [comment]
Yes, I'm going to do that soon, within 1-2 days maximum.

**Comment by ad71** [comment]
Great!

**Comment by kunwar31** [comment]
Thanks @ad71

**Comment by kunwar31** [comment]
@ad71 I've implemented HybridWumpusAgent class, left with plan_route() and plan_shot() helper functions

**Comment by ad71** [comment]
Nice work! After you complete the remaining functions, make sure you add a few simple tests to see if everything works as intended.

**Comment by norvig** [comment]
Looks good. I think a lot more could be done with `Expr` objects rather than string concatenation. That is, rather than `"FacingEast(" + str(t) + ")"` you could just have  `FacingEast(t)` if you have already defined `FacingEast` as an `Expr` function.

**Comment by kunwar31** [comment]
@norvig Thanks for the suggestion. I will try to refactor it.

**Pull request merged**
