### PR TITLE
Added TicTacToe to notebook

### PR DESCRIPTION
**Pull request by Chipe1**
You can now play TicTacToe with human, random or alphabeta player

### CODE REVIEW

**Comment by Chipe1** [comment]
@norvig  This PR overwrites #211 . So that PR needs to be reverted to resolve the conflict.

**Comment by norvig** [comment]
@Chipe1 I'm not sure how to revert #211

**Comment by Chipe1** [comment]
@norvig https://help.github.com/articles/reverting-a-pull-request/ . Maybe that might work

**Comment by reachtarunhere** [comment]
@Chipe1 @norvig I have a suggestion. We should move the canvas.js file to the js directory so as to keep things organized. So before this is merged maybe @Chipe1  can make the required changes.

**Comment by SnShine** [comment]
Need some inputs here. Which name would be nice for the interactive game `Interactive_TicTacToe` or `Canvas_TicTacToe`?
Right now, we are having js files in js folder as mentioned by @reachtarunhere. It would be better if we move js files to this folder. 
And, would it be nice to have `ipyviews.py` and `canvas.py` in the same file?

And @norvig reverting a PR is easy but it creates one more PR while reverting. It would be better if @Chipe1 can rebase/merge this branch with updated master branch and push a new commit to resolve conflicts.

**Comment by reachtarunhere** [comment]
@SnShine  I like the idea of having content of canvas and and ipyviews together in ipyviews. But the issue is that I am not sure how well the canvas file follows the model view architecture. Overall it would be a good idea to have them together. I am also writing a ipynotebook for ipyviews explaining the usage. Probably @Chipe1  can then add to it and we can have a good doc on how to use his general canvas implementation.

**Comment by Chipe1** [comment]
I fixed the conflict and moved canvas.js to js folder

**Pull request merged**
