### PR TITLE
Fix #741: Add learning agent to vacuum_world.ipynb

### LINKED ISSUE #741: Add Learning Agent to vacuum_world.ipynb
Hello, @norvig and @MrDupin! Currently, `vacuum_world.ipynb` discusses all the basic kinds of agent programs that embody the principles underlying almost all intelligent systems.  
I am planning to add an explanation and a schematic diagram of the learning agent in `vacuum_world.ipynb` as well.
Please suggest.  
Thanks!

### PR DESCRIPTION
**Pull request by apb7**
This PR:  
* Fixes #741 
* Adds explanation for general learning agent.
* Adds schematic diagram for the agent as well, as given in the book.  

@norvig and @MrDupin: Please review this PR.  
Thanks!

### CODE REVIEW

**Comment by apb7** [comment]
@MrDupin: The Travis build fails due to the recently added `assert policy_iteration(sequential_decision_environment_3)` test although I have not changed the mdp.py file. This test was added in PR #722.  
@ad71: Can you please look into this?  
Thanks!

**Comment by ad71** [comment]
Sure @apb7 , I'm on it.

**Comment by ad71** [comment]
The checks have passed now, so it's fine I guess.

**Comment by apb7** [comment]
@ad71: I guess the test is flaky. Please try it locally. It should not have failed the first time as well.  
Thanks!

**Comment by ad71** [comment]
I had checked this test several times on my local machine before submitting the PR. But you might be right. I'll look into it

**Comment by ad71** [comment]
You were right. The optimum policy had two different possibilities with the exact same cost which caused policy iteration to pick a random state out of the two. I'm sorry for the inconvenience and thanks for pointing out the mistake. The test has been removed in #743

**Pull request merged**
