### PR TITLE
Adding Tkinter GUI

### PR DESCRIPTION
**Pull request by apb7**
* Issue #659   
* Added `vacuum_agent.py` and `xy_vacuum_environment.py`. 
* `vacuum_agent.py` creates a GUI for the two-tiles vacuum environment.  
* `xy_vacuum_environment.py` creates a GUI for the two-dimensional dynamic vacuum environment which       can be changed at any point of time by the user.

### CODE REVIEW

**Comment by apb7** [comment]
Hello @norvig and @MrDupin! Can you please review this once?  
Thanks!

**Comment by MrDupin** [comment]
What agent is the `xyEnvironment` implementing? It is not very useful, it seems to be going off in random directions, even when dirt is right next to the agent. Is it how it's supposed to work? Also, the 'click-to-change-tile' method is a bit clunky. Right now it rotates globally around W/D/Empty. It would be best if it was the individual tile was rotating around the options. I think this can be implemented by checking the tile value when the user clicks on it. If it is 'D', it becomes empty, if it is 'W' it becomes 'D' and if it is Empty it becomes 'W' (or something along these lines). I think that would make things easier.

In `vacuum_agent.py`, the scenes appears too low on the window. Is it possible to get it centered? Apart from that, I would like to see the hover-over color of the buttons changed. If I hover over a Dirt tile, it should become a dark brown, and if I hover over an Empty tile, it should become gray. Right now the button becomes gray no matter what its value is, and it is a bit confusing. Also, the left button doesn't seem to work when I press it.

**Comment by apb7** [comment]
@MrDupin: Currently the `xyEnvironment` is using `random.choice` to generate its next action: If the percept is 'Bump', it has 50% probability to go right and 50% to go left. If the tile is clean, there is 25% probability to go right, 25% to go left and 75% to move forward (Similar to that of the `EnergeticBlindDog` given in the notebook): [XYReflexAgentProgram](https://github.com/apb7/aima-python/blob/gui/gui/xy_vacuum_environment.py#L127:L143). This can be changed whenever we plan to expand the idea!  
And yes! I also found the click-to-change-tile a bit clunky. I'll incorporate your idea there :)
In `vacuum_agent.py`, I can surely center the scene. Although I am not sure if the hover-color can be changed according to the button. Nevertheless, I'll look around for a way. And, the left button works for me though I'll check it once again!  
Thanks, for an in-depth review!

**Comment by MrDupin** [comment]
Ah, got it. The `xy_environment` is fine then. Looking forward to seeing this expanded!

**Comment by apb7** [comment]
Thank you @MrDupin! I'll make other changes soon.

**Comment by apb7** [comment]
Hello @norvig and @MrDupin! I have made the changes. The hover-over-color now changes according to the block color: a light brown for dirty block and gray for a clean block. I have centered the scene in `vacuum_agent.py` and made sure that all the buttons work.  
For the `xy_environment`, click-to-change-tile works in the same way as suggested above.  
Please suggest further improvements!  
Thanks!

**Comment by MrDupin** [comment]
I like the changes, nice work!

**Comment by apb7** [comment]
Thank you @MrDupin!

**Pull request merged**
