### PR TITLE
Genetic Algorithm: Threshold

### PR DESCRIPTION
**Pull request by MrDupin**
Added a function, `fitness_threshold`, to clean up the main function a bit. The function used to have a nested if-condition, which I have now removed.

Another improvement that can be made is changing

```
if fittest_individual:
    return fittest_individual
```

to the one-line alternative

```
if fittest_individual: return fittest_individual
```

But I am not sure this will be stylistically the same with the rest of the code.

### CODE REVIEW

**Comment by norvig** [comment]
Personally, I think the one-line if statement is fine, but I think PEP 8 discourages it.

**Comment by heisenbuug** [comment]
Hello, i want to continue your work in GSOC 2018, so can you just give me details of your project so i can see what more can i contribute. I am proficient in Python and C++. I am well versed with concepts of machine learning deep learning. I have done some work using openCV and currently I am getting into the book.

**Comment by MrDupin** [comment]
Hello @heisenbuug! You can check out what you can do in the [contributing.md](https://github.com/aimacode/aima-python/blob/master/CONTRIBUTING.md).

**Comment by heisenbuug** [comment]
Thanks man!!! I will go through everything and will get back to you soon. BTW is aima applying as organisation this year in Gsoc?

**Comment by MrDupin** [comment]
I think the organizations will be announced on the 12th of February.

**Pull request merged**
