### PR TITLE
Added virtualenv instructions

### LINKED ISSUE #754: Add virtualenv installation details in CONTRIBUTING.md
If someone is having both python 2.x and python 3.x, it becomes essential to create virtualenv to separate both.
Also new users who are not aware of this may feel stucked. 

This will help users to create virtual environment before getting started.

I will be adding a PR. See if it makes things easier for others. 

Any admin here to comment on this issue?

### PR DESCRIPTION
**Pull request by umangahuja1**
Fixes #754 

Added virtualenv installation details that will ease out testing process too.

@MrDupin have a look

### CODE REVIEW

**Comment by MrDupin** [comment]
I am not that familiar with `virtualenv` so I can't provide any concrete feedback.

**Comment by umangahuja1** [comment]
Actually this will help to distinguish modules between python2 and 3 version to avoid any complexities and errors. Anyone else here whom I can refer to validate.

Also I would be thankful if you can tell how should I approach in this community. I am a GSoC aspirant and went through all the guidelines.

**Comment by apb7** [comment]
Hello, @MrDupin! I am quite familiar with  `virtualenv`.   
@umangahuja1: There are a few points of concern (which I feel):  
1. Using `virtualenv` just for testing purposes does not seem to be justified since there is only one module, `pytest` which needs to be installed. This can easily be done by `pip3 install pytest`.  
2. Setting up `virtualenv` takes some time which again could be avoided by using `pip3` instead of `pip`.  3. If we intend to use it for the complete repository, we will have to install all the third-party libraries we use. This might lead to a bit complicated procedure since all we want is that the reader can quickly run the notebooks and go through them.  

Please feel free to correct me at any point. I'll be happy to discuss it :)

**Comment by umangahuja1** [comment]
Most of the part you are correct. 

But I was working with ubuntu and had pytest alreay installed both python2 and python3 version. Hence when I was running it by default as py.test, it was running with python2 and that resulted in 14 errors and that's when I felt this can be case with others too.

We can discuss more since I feel it can happen with others too plus some beginners will also get to learn more about virtualenv this way(maybe).

**Comment by apb7** [comment]
@umangahuja1: I think your problem could be solved by using `pip3 install pytest` instead of `pip install pytest` (which we can change in `CONTRIBUTING.md`).  
Thanks!

**Comment by umangahuja1** [comment]
No I did that part and still it was not solved reason being I had both pytest with python2 and 3 version installed. Hence it was not possible to distinguish between them.

**Comment by apb7** [comment]
@umangahuja1: Okay! Understood :)

**Comment by umangahuja1** [comment]
So I think this will be helpful and also if we at any point of time want to add more dependencies, using virtualenv will be a good practice.

What's your say.

**Comment by apb7** [comment]
@umangahuja1: I think we should leave this for the collaborators to decide for now :)

**Comment by umangahuja1** [comment]
Sure :) At least for me the problem is solved so I will look to contribute more on other issues and pseudocodes.

**Comment by norvig** [comment]
I don't see a compelling argument for why we need to add the complication of `virtualenv`. Everything we do should be in Python 3.

**Pull request closed without merging**
