### PR TITLE
Removed errors to make the build pass

### PR DESCRIPTION
**Pull request by articuno12**
Removed flake8 errors causing build to fail.

### CODE REVIEW

**Comment by RojerGS** [comment]
@articuno12, the build still has some flake8 errors. Will you address those?

**Comment by articuno12** [comment]
@RojerGS Yup . Already working on them .

**Comment by articuno12** [comment]
Added the minor change done by @RojerGS so that build fail is checked in a single PR.

**Comment by RojerGS** [comment]
I will close #420 as my bug fix is corrected here and my PR didn't fix the flake8 errors.

**Comment by Chipe1** [comment]
@articuno12 You forgot whitespaces around '+'
I've made a PR with the fix to while loop included for my local tests to pass. Could you change it to prevent merge conflicts.

**Comment by Chipe1** [comment]
I've removed flake8 errors for the new commits in #508

**Pull request merged**
