### PR TITLE
Fix #731: Add table and tests for TableDrivenVacuumAgent

### LINKED ISSUE #731: Add table and tests for Table Driven Vacuum Agent
Hello, @norvig and @MrDupin! Currently, we have tests for `RandomVacuumAgent`, `ReflexVacuumAgent` and `ModelBasedVacuumAgent`. I would like to add a test for `TableDrivenVacuumAgent` as well.  
Also, the table for the `TableDrivenVacuumAgent` is not complete. We need to implement it before the test goes in.  
Thanks!

### PR DESCRIPTION
**Pull request by apb7**
This PR:  
* Fixes #731 
* Implements the table for the `TableDrivenVacuumAgent` in the `TrivialVacuumEnvironment`
* Adds a test for `TableDrivenVacuumAgent` in the `TrivialVacuumEnvironment`

@norvig and @MrDupin: Please review this PR.  
Thanks!

### CODE REVIEW

**Comment by apb7** [comment]
@MrDupin: I tried the test locally. It produces no error but here on Travis, the final status of the environment is shown as `{(0,0):'Clean' , (1,0) : 'Dirty'}`.  Am I going wrong somewhere?  
Thanks!

**Comment by MrDupin** [comment]
I am afraid I also get the same error.

Did you change anything in `agents.py`, or did you just add the test? Maybe you have set the `random.seed` somewhere? Travis for some reason doesn't take the `random.seed` into consideration.

**Comment by apb7** [comment]
@MrDupin: I have just added the test. I did not change any another file or set `random.seed` anywhere else. The added test runs without an error locally.

**Comment by MrDupin** [comment]
I noticed that the function `TableDrivenVacuumAgent` possibly has parts of the table missing. The function has some `# ...` lines, which probably means the values in the middle are omitted. I don't have the book handy at the moment, can you make sure there are no values missing?

**Comment by apb7** [comment]
@MrDupin: Oh, I also noticed the same thing. Let me look into the book once. Thanks for your help! :)

**Comment by apb7** [comment]
@MrDupin: I could not find the table for two-state vacuum environment in the book. For the table-driven agent, it states the general pseudocode. I'll look into the table once. Thanks!

**Comment by apb7** [comment]
So @MrDupin, I found out that the table is not complete. If we set both the locations of the Trivial Vacuum Environment to Dirty, the agent does not clean up location B (1,0). Therefore we need to complete it before we implement a test for it.  Thanks!

**Comment by apb7** [comment]
@MrDupin: I've implemented the table for the agent. Please review it once!  
Thanks!

**Pull request merged**
