### PR TITLE
Added Random Forest Learner in learning.ipynb

### PR DESCRIPTION
**Pull request by CharuChhimpa**
Refrencing issue #844 
Also added an image file in images folder

### CODE REVIEW

**Comment by ad71** [comment]
Nice work! Are you sure we can use the image without giving credits to the original author?

**Comment by CharuChhimpa** [comment]
@ad71 ,Sorry I forgot to mention the souce. Should I mention it?

**Comment by ad71** [comment]
The image is from kaggle, but I don't know if you are allowed to use it without the original author's permission. It may not be a big deal, but I think you can mention the source.

**Comment by norvig** [comment]
Nice work.

**Pull request merged**
