### PR TITLE
Add Heuristics for A* search

### PR DESCRIPTION
**Pull request by Dragneel7**
#671 
With 8Puzzle problem as example, show heuristics for A* search to solve the puzzle.

### CODE REVIEW

**Comment by Dragneel7** [comment]
@MrDupin @norvig Please review this PR. Can this be a useful as a suitable example for the concept.

**Comment by apb7** [comment]
Hello @norvig and @MrDupin! While opening `search.ipynb` now, the following error is encountered:
  
screenshot-localhost-8888-2018-01-11-10-30-03-094

I think it might be due to the latest commit to `search.ipynb`. @Dragneel7 can you please confirm this once?  
Thanks!

**Comment by Dragneel7** [comment]
@apb7 Sure I will look into it.

**Comment by Dragneel7** [comment]
@apb7 @norvig @MrDupin I looked into the problem maybe my work and apb7's work on the same file resulted in some merge conflicts. Can I add another PR correcting this mistake.

**Comment by apb7** [comment]
Hello @Dragneel7! I think the merge conflict exists only due to the fact that the order of states which you have used in Line 216 is different from that used in the notebook previously and not because of changes done by me. Using the same order as stated earlier will resolve this.  
Thanks!

**Comment by MrDupin** [comment]
Anyone can make a PR with a fix as soon as you have it, no problem.

**Comment by Dragneel7** [comment]
@apb7 @MrDupin I removed the merge conflicts but the notebook is still not rendering on github, it is getting rendered on my laptop and any other laptop after cloning but I am not sure of the reason why this is happening.
The best I can guess is:-
deepinscreenshot_20180112041748
is this error. I have matplotlib installed but still this error persists.
I am trying my best to resolve this, but if things don't work out I guess we will have to revert back to the previous stable version.Sorry for the trouble, I will try my best to fix it as soon as possible.

**Comment by MrDupin** [comment]
To work on a fix, can someone open a new issue? Discussing this on a closed PR will not get much attention.

**Comment by Seenivasanseeni** [comment]
On running `search.ipynb`  i got error stating no such file found:  aima-python/aima-data/orings.csv . do i need to run any scripts for it.

**Comment by MrDupin** [comment]
@Seenivasanseeni: Did you run `git submodule init` and `git submodule update` in your directory?

**Comment by Seenivasanseeni** [comment]
on running ` git submodule update`, it prints the follow up  and stays there long time. Does it need such time?
`Cloning into '/home/seeni/aima-python/aima-data'...
`

**Comment by MrDupin** [comment]
Yes, give it time. It downloads all the data from the corresponding repo.

**Comment by Seenivasanseeni** [comment]
Yeah. I got that done.

**Comment by Seenivasanseeni** [comment]
But i got no error as mentioned in [https://user-images.githubusercontent.com/24193342/34851415-e321f73c-f74f-11e7-9e5b-799e93c8cb56.png](url). I got everything without any errors after submodule update.

**Comment by MrDupin** [comment]
I think I fixed the error in #726. I am waiting for the PR to get merged.

**Pull request merged**
