### PR TITLE
Solve Issue of Loading search.ipynb

### PR DESCRIPTION
**Pull request by Dragneel7**
#688

### CODE REVIEW

**Comment by Dragneel7** [comment]
@MrDupin I have solved this issue, I just have to rebase it with master and then it is ready to go.
@varunvora Are you working on this? I started working on it as no one had claimed the issue and the errors were because of conflicts in mine and abp7's code.

**Comment by Dragneel7** [comment]
@norvig @MrDupin Please review the PR. I have fixed the issue and cleaned the code in accordance to the coding trend of the repository  with the algorithm in  "search.py" and only the heuristics and results in the notebook.
@apb7 Kindly check if the issue was resolved.
Thanks.

**Comment by MrDupin** [comment]
I believe the issue is resolved here. Nice work!

**Comment by apb7** [comment]
Hello @norvig and @MrDupin! The issue seems to be resolved. Just a little doubt, @Dragneel7, shouldn't we remove the '0' tile as the 8 puzzle problem has 8 tiles and a space to move the tiles (which is in conformity with the problem stated in the book). Also, this has been mentioned in the notebook as well:  
>The 8 Puzzle Problem consists of a 3x3 tray in which the goal is to get the initial configuration to the goal state by shifting the numbered tiles into the blank space. 

Please feel free to correct me!  
Thanks!

**Comment by Dragneel7** [comment]
@apb7 That is true, I had intended to mention this in the description of the program to treat the tile 0 as blank. I guess I forgot to do the same.
Still with the example diagram it is pretty clear what is happening, moreover we are concerned not with solving the problem but with the heuristics that solve it, So i guess '0' works fine too.
Thuough it won't be any trouble to change it.

**Comment by MrDupin** [comment]
I noticed a little typo, if you can get it fixed. In the "A* Heuristics" chapter, in the first sentence you write:

"Different heuristics provide different have different efficiency"

Where you write both "provide different" and "have different". You should choose one or the other (I think the first sounds better).

**Comment by Dragneel7** [comment]
@norvig The python notebooks are not getting rendered, it's maybe due to the issue that is being solved by this PR. Can you please look into the matter.
Thanks

**Pull request merged**
