### PR TITLE
Implementing HITS algorithm

### PR DESCRIPTION
**Pull request by thundergolfer**
Implementing HITS algorithm as faithfully to pseudo-code as I could. 

Closed previous pull requests because of an error in convergence detection. Hadn't had enough coffee sorry.

### CODE REVIEW

**Comment by SnShine** [comment]
Hey @thundergolfer,

This PR looks fabulous. Can you put all of this into `nlp.py` rather than in a new rank module?

**Comment by thundergolfer** [comment]
@SnShine yeah I can do that. Should I do it and then resubmit the pull request?

**Comment by SnShine** [comment]
No need to submit a new PR. Put the code & tests into nlp and test_nlp files and commit. Push that new commit to your branch `devHITS`. It will appear in this PR.

**Comment by thundergolfer** [comment]
@SnShine Ah cheers will do.

**Comment by thundergolfer** [comment]
@SnShine Code has been moved :)

**Pull request merged**
