### PR TITLE
Add Perceptron to Notebook

### PR DESCRIPTION
**Pull request by MrDupin**
Added a new section to the Python Notebook for the Perceptron Classifier. Currently includes Overview and Implementation. I have also written an example for the learner, but I will add it once #333 is resolved.

### CODE REVIEW

**Comment by MrDupin** [comment]
Added example to Perceptron Learner section. The section is now complete.

**Comment by sofmonk** [comment]
the build fails because of flake8 errors in test_agents.py and test_text.py , 
fixed that in PR #373 ,will have to wait for merge.

**Comment by sofmonk** [comment]
the build fails due to --test_text.py and test_agents.py, it shows flake8 errors, fixed that in PR #373 , will have to wait for merge

**Comment by MrDupin** [comment]
Updated the PR with some minor fixed in the notebook.

**Comment by MrDupin** [comment]
(closing this to make a cleaner PR)

**Pull request closed without merging**
