### PR TITLE
TODO (completed): Move >>> doctests from utils.py to utils_test.py

### PR DESCRIPTION
**Pull request by SnShine**
Here are the changes:
* Moved all the >>> doctests from utils.py to utils_test.py
* Fixed bugs in argmin_list & argmax_list methods
* Modified how argmax_list & arg_max are defined. Old methods fail if the fn is len.
* Modified print statements to Python3 style in agents.py

### CODE REVIEW

**Comment by norvig** [comment]
Nice work @SnShine. I'd like to merge this, but as a github newbie, I don't see how to do it easily. Is there a way to do the merge in Github Desktop? Or do I have to issue shell commands? Or can you easily put in a new pull request against the current state of the repository?  Thanks -- I'll get the hang of this yet ...

**Comment by SnShine** [comment]
Thank you.
Yeah, I will rebase my branch 'addPytests' to resolve conflicts in utils.py. Then you can merge it as a normal pull request.

**Comment by SnShine** [comment]
Yeah, @norvig, I have resolved the conflicts. You can merge now as you are merging normal pull request.

**Comment by norvig** [comment]
Thanks @SnShine, good  work.

**Comment by tmrts** [comment]
@norvig I don't we should remove doctests of functions, because they provide clean examples. I believe it would be better if we have comprehensive tests in `*_test.py` and readable usage examples as doctests. 

Of course doctests at the end of files should be translated to proper tests.

**Comment by norvig** [comment]
@tmrts and @SnShine I agree with your points

Good point. I think there are two purposes of tests: examples, and true tests. 

For functions where it is not immediately obvious how to use them, it would be good to have exactly one example in the docstring.  For example:

def product(numbers):
    """Return the product of the numbers.
    >>> product([2, 3, 4])
    24"""

What we don't want is a long collection of true tests in the docstring that cover all the corner cases (one number, no numbers, zeroes, etc.).

**Pull request merged**
